name: Continious integration (CI)

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
      NAME_OWNER:
        required: true
    inputs:
        VERSION:
          required: false
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Prepare before build
      run: sudo apt-get update -y

    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.NAME_OWNER }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and test package
      run: |
        echo OK
