on:
  push:
    branches:
      - main

jobs:
  build:
    uses: aflatoune/consotracker/.github/workflows/build.yml@main
    with:
      VERSION: latest
      NAME_APP: consotracker

  push:
    runs-on: ubuntu-latest
    needs: build
    env:
      NAME_APP: consotracker
      VERSION: latest
      OWNER: ${{ github.repository_owner }}
    steps:

      - name: Prepare before build
        run: sudo apt-get update -y

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Download build-output artifact
        uses: actions/download-artifact@master
        with:
          name: image-docker

      - name: Read artifact
        run: |
          docker load -i docker-image.tar

      - name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_TOKEN }}
          password: ${{ secrets.HEROKU_USERNAME }}

      - name: Push on Heroku registry and deploy
        run: |
          bash ci/heroku/deploy.sh

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.NAME_OWNER }}
          password: ${{ secrets.TOKEN }}

      - name: Push on ghcr registry
        run: |
          bash ci/github/push.sh




