on:
  push:
    branches:
      - main

jobs:
  build:
    uses: aflatoune/consotracker/.github/workflows/build.yml@main
      with:
        VERSION: latest
        NAME_APP: consotracker
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push:
    runs-on: ubuntu-latest
    needs: build
    env:
      NAME_APP: consotracker
      VERSION: latest
      OWNER: ${{ github.repository_owner }}
    steps:

      - name: Download build-output artifact
        uses: actions/download-artifact@master
        with:
          name: build-output
          path: build/

      - name: Login to Heroku Registry
        uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_TOKEN }}
          password: ${{ secrets.HEROKU_USERNAME }}

      - name: Push on Heroku registry and deploy
        run: |
          bash ci/heroku/deploy.sh

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.NAME_OWNER }}
          password: ${{ secrets.TOKEN }}

      - name: Push on ghcr registry
        run: |
          bash ci/github/push.sh




